// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: musica
			/// 2D
			/// </summary>
			public const string musica = "musica";

			/// <summary>
			/// Tag: sfx
			/// 2D
			/// </summary>
			public const string sfx = "sfx";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: capa
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string capa = "capa";

			/// <summary>
			/// Variable: musica
			/// Range: [0 - 2]
			/// Type: Local
			/// </summary>
			public const string musica = "musica";

			/// <summary>
			/// Variable: realidad
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string realidad = "realidad";

			/// <summary>
			/// Variable: sfx
			/// Range: [0 - 5]
			/// Type: Local
			/// </summary>
			public const string sfx = "sfx";

		}

		public class Channels
		{
			public const string Master = "Master";

		}
	}
}
